"""init

Revision ID: d739f7c6a2ed
Revises: 
Create Date: 2025-09-16 16:55:30.206550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd739f7c6a2ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('subscriptions_order_id_key'), 'subscriptions', type_='unique')
    op.create_index(op.f('ix_subscriptions_order_id'), 'subscriptions', ['order_id'], unique=True)
    op.drop_constraint(op.f('fk_subscriptions_users'), 'subscriptions', type_='foreignkey')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('users', 'role')
    op.drop_column('videos', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role', sa.TEXT(), server_default=sa.text("'student'::text"), autoincrement=False, nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_foreign_key(op.f('fk_subscriptions_users'), 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_subscriptions_order_id'), table_name='subscriptions')
    op.create_unique_constraint(op.f('subscriptions_order_id_key'), 'subscriptions', ['order_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('subscriptions', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
