[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# если нужно проксировать API запросы на твой бэкенд
[[redirects]]
  from = "/api/*"
  to   = "https://telegram-expertlash-bot-production.up.railway.app/:splat"
  status = 200
  force = true
